### ISSUE TITLE
VPN connection status is Down

### ISSUE THREAD

**Issue by pamandrejko** [ibm-cloud-docs/solution-tutorials#82]
Tutorial: [Using a VPC/VPN gateway for secure and private on-premises access to cloud resources ](https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-site2site-vpn)

We've configured a VPC in IBM Cloud with no external internet connection and deployed OpenShift to it. Now we are using the tutorial to configure a VPN gateway.

Everything is working well but we have 1 question. After we completed the step [Create the Virtual Private Network gateway and connection](https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-site2site-vpn#vpc-site2site-vpn-create-vpn), the VPN gateway status is Active but when we open it the VPN connection status is Down.

We were wondering if that is expected at this point since we still have to complete the next step [Create the on-premises Virtual Private Network gateway](https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-site2site-vpn#vpc-site2site-vpn-10)?

**Comment by powellquiring** [comment]
I believe the "down" is expected because the on-prem is not active yet. The shown public IP address and the "enabled" are a success indicator.
down->up once the on-prem side is connected

This could be clarified?  It is this section, right?

![image](https://user-images.githubusercontent.com/6932057/117009158-4ce8c480-aca0-11eb-82e0-6e55ba8bf47e.png)

How about if we add the following text in the red box:

- The VPN connection status will be down until the peer on-premises Virtual Private Network gateway is created.

**Comment by pamandrejko** [comment]
That would be perfect. Thank you!

**Comment by powellquiring** [comment]
fixed
